site_name: Arrowhead navodila za uporabo
theme:
  name: material
  custom_dir: overrides
  language: sl
  palette:
    primary: indigo
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/field.ico

nav:
  #- 🇬🇧 En:
  #    - Instead of an introduction: en/getting-started.md
  #    - Position: en/position.md
  #    - Left - right: en/left-right.md
  #    - Distances: en/distances.md
  #    - Distance Estimation: en/estimation.md
  #    - Test: en/test.md
  #    - Oblique throw: en/graph.md
  #    - Sofa: en/sofa.md
  #    - Before the competition: en/other.md
  #    - Calculator: en/calculate.md
  #    - Finally: en/about.md
  #    - Opinions: en/feedback.md
  - 🇸🇮 Sl:
      - 🏁 Namesto uvoda: sl/getting-started.md
      - 📖 Zgodba o poševnem metu: sl/graph.md
      - 🎯 Ocenjevanje razdalj:
          - 🟢 Osnove: sl/estimation/basic.md
          - ⚡ Metode: sl/estimation/estimation.md
          - 📏 Razdalje: sl/estimation/distances.md
          - 📝 Test viziranja: sl/estimation/test.md
          - 📋 Plonk listek: sl/estimation/chat-sheet.md
      - 🧠 Za radovedne glave:
          - ↗️ Poševni met: sl/theory/theory.md
          - ⚛️ Fizikalne osnove: sl/theory/index.md
          - 🔄 Skrivnostni obrat: sl/theory/mystery.md
      - 🌀 Optične prevare:
          - 🟢 Osnove: sl/illusions/index.md 
          - 🏹 Arrowhead: sl/illusions/illusions.md
          - 🌲 Vpliv terena: sl/illusions/left-right.md
          - ☀️ Vpliv sonca: sl/illusions/sun.md
          - 🔍 Primeri:
                - 📐 Geometrijske iluzije: sl/illusions/geometry.md
                - ✏️ Iluzorne konture: sl/illusions/contures.md
                - 🎨 Svetlobne iluzije: sl/illusions/colors.md
                - ❌ Nemogoči predmeti: sl/illusions/impossible.md
                - 🗂️ Ostalo: sl/illusions/misc.md
      - 📍 Postavitev:
                - ravno: sl/position/position-flat.md
                - postrani: sl/position/position-slope.md
                - rotacija: sl/position/rotation.md
      - 🛋️ Kavč: sl/sofa.md
      - 🏁 Pred tekmovanjem: sl/other.md
      - 🧮 Kalkulator: sl/calculate.md
      - 🏋️ Priprave:
          - 📅 Na kratko: sl/training.md
          - 📊 Tiskanje:
                - tabele: sl/print/print.md
                - rotacija: sl/print/print-foot.md
                - postavitev gor: sl/print/print-up.md
                - postavitev dol: sl/print/print-down.md
      - 🎬 Za konec: sl/about.md
      - 💬 Mnenja: sl/feedback.md


  #- 🇷🇸 Sr:
  #    - Уместо увода: sr/getting-started.md
  #    - Распоред: sr/position.md     
  #    - Лево - Десно: sr/left-right.md
  #    - Удаљености: sr/distances.md
  #    - Процена удаљености: sr/estimation.md
  #    - Тест: sr/test.md
  #    - Косо бацање: sr/graph.md
  #    - Софа: sr/sofa.md
  #    - Пре такмичења: sr/other.md
  #    - Калкулатор: sr/calculate.md
  #    - Коначно: sr/about.md
  #    - Мишљења: sr/feedback.md

# plugins:
#  - search
plugins:
  - search:
      enabled: false
  # - pdf-export
  # - with-pdf:
  #    cover_title: Moj Dokument
  #    cover_subtitle: Verzija 1.0
  #    output_path: dokument.pdf

extra_css:
  - stylesheets/extra.css
  - stylesheets/arrowhead.css
  - stylesheets/print.css

markdown_extensions:
  - md_in_html
  #- pymdownx.arithmatex:
  #    generic: false


extra_javascript:
  - js/global.js
  - js/language_switcher.js
  - js/login.js
  - js/print.js
  # - js/logout.js
  #- js/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
#  search:
#    language: en
  alternate:
    #- name: 🇬🇧 English
    #  link: en/getting-started
    - name: 🇸🇮 Slovenščina
      link: sl/getting-started
    - name: 🇷🇸 Srpski
      link: sr/getting-started
